#!/bin/bash
#
# Copyright (c) 2022 Apfelwerk GmbH & Co. KG
# # # # # # # # # # # Jamf Protect # # # # # # # # # # # 
# Title: Security Auditing Enabled
# CIS Nr.: 3.1
# Level: 1
# Type: Auditing
# Info: macOS's audit facility, auditd, receives notifications from the kernel when certain system calls, such as open, fork, and exit, are made. These notifications are captured and written to an audit log.
# Rationale: Logs generated by auditd may be useful when investigating a security incident as they may help reveal the vulnerable application and the actions taken by a malicious actor.
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
# Version 1.0 edited by Manuela Munoz Bocanegra on 2022-05-27
# Audit: Perform the following to verify that security auditing is enabled
sudo launchctl list | grep -i auditd
# Output: - 0 com.apple.auditd
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
